- hosts:  ent-search-node
  tasks:
    - service:
        name: enterprise-search.service
        state: stopped
      become: true     
    - yum:
        name: enterprise-search
        state: absent
      become: true
    - ansible.builtin.systemd:
        daemon_reexec: yes
      become: true
    - file:
        path: "{{item}}"
        state: absent
      with_items:
        - /usr/share/enterprise-search/
        - /var/log/enterprise-search/
      become: true
