- name: Download sample apache log file for testing the file input pipeline
  hosts: logstash-node
  tasks:
    - name: Download the file
      get_url:
          url: https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/apache_logs/apache_logs
          dest: /tmp/access_log
