- hosts: logstash-node
  tasks:
    - service:
        name: logstash.service
        state: stopped
      become: true
    - yum:
        name: logstash
        state: absent
      become: true
    - ansible.builtin.systemd:
        daemon_reexec: yes
      become: true
    - file:
        path: "{{item}}"
        state: absent
      with_items:
        - /etc/logstash
        - /usr/share/logstash
        - /var/lib/logstash
        - /tmp/.sincedb
        - /tmp/access_log
        - /tmp/.jdbc_last_run
        - /tmp/.logstash_jdbc_last_run
      become: true